import { ArrowRight, Bell, CalendarDays, CheckCircle2, ChevronRight, CircleUserRound, Clock3, ExternalLink, FileText, LayoutDashboard, ListChecks, MessageSquare, Settings, ShieldCheck, Sparkles, Trophy, UserRound, Vote, Wallet, Zap } from 'lucide-react'
import { Link, NavLink, Navigate } from 'react-router-dom'
import { Eyebrow, Stat, StatusChip } from '../components/UI'
import { tasks } from '../data/content'

function MemberNav({ wallet }) {
  return <aside className="member-sidebar"><div className="member-id"><span>{wallet.address?.slice(2,4).toUpperCase()}</span><div><b>Community member</b><small className="mono">{wallet.address?.slice(0,7)}…{wallet.address?.slice(-5)}</small></div></div><nav><NavLink to="/app/dashboard"><LayoutDashboard/> Overview</NavLink><NavLink to="/app/tasks"><ListChecks/> My tasks <span>2</span></NavLink><NavLink to="/app/profile"><UserRound/> Profile</NavLink><NavLink to="/governance"><Vote/> Governance</NavLink><NavLink to="/app/notifications"><Bell/> Notifications <span>3</span></NavLink></nav><div className="member-sidebar__foot"><span><ShieldCheck/> Connected to</span><b>{wallet.networkName || 'Redbelly Mainnet'}</b><i><em/></i></div></aside>
}

export function MemberLayout({ wallet, children }) {
  if (!wallet.address) return <Navigate to="/" replace />
  return <div className="member-shell"><MemberNav wallet={wallet}/><div className="member-content"><header className="member-mobile-head"><span>Member space</span><span className="mono">{wallet.address.slice(0,5)}…{wallet.address.slice(-4)}</span></header>{children}</div></div>
}

export function DashboardPage({ wallet }) {
  return <MemberLayout wallet={wallet}><div className="member-page"><div className="member-page-head"><div><Eyebrow>Redbelly overview</Eyebrow><h1>Good afternoon, Alex.</h1><p>Here’s what’s happening across Redbelly, with your activity close at hand.</p></div><button className="button button--secondary"><Bell size={16}/> 3 new</button></div>
    <div className="attention-grid"><article className="attention-card attention-card--red"><span className="icon-box"><Vote/></span><div><span>Governance · Action needed</span><h2>Cycle 2 taskboard rules</h2><p>Voting closes in 2 days. Review the changes and cast your vote.</p><Link to="/governance">Review proposal <ArrowRight size={15}/></Link></div><strong>2d</strong></article><article className="attention-card"><span className="icon-box"><CalendarDays/></span><div><span>Upcoming ecosystem event</span><h2>Builder Guild office hours</h2><p>Tomorrow, 16:00 UTC · Discord Stage</p><a href="#calendar">Add to calendar <ExternalLink size={14}/></a></div></article></div>
    <div className="dashboard-stats"><Stat label="Products & projects" value="24" detail="7 active this cycle"/><Stat label="Your active tasks" value="02" detail="1 due this week"/><Stat label="RBNT earned" value="1,840" detail="Across 6 contributions"/><Stat label="Votes cast" value="05" detail="71% participation"/></div>
    <div className="dashboard-grid"><section className="dash-panel"><header><div><Eyebrow>Your work</Eyebrow><h2>Active tasks</h2></div><Link to="/app/tasks">View all <ArrowRight size={14}/></Link></header>{tasks.slice(0,2).map((t,i)=><article className="my-task" key={t.id}><div><span className="mono">{t.id}</span><StatusChip>{i ? 'Review' : 'In progress'}</StatusChip></div><h3>{t.title}</h3><div className="progress"><i style={{width:`${i ? 94 : 72}%`}}/></div><footer><span>{i ? 'Submitted 2 days ago' : 'Due in 6 days'}</span><b>{i ? '94%' : '72%'}</b></footer></article>)}</section><section className="dash-panel"><header><div><Eyebrow>Ecosystem pulse</Eyebrow><h2>Recent activity</h2></div></header><div className="activity-feed"><article><span><CheckCircle2/></span><div><p><b>RCDP-06</b> was executed</p><small>Community Showcase pilot funded · 32m</small></div></article><article><span><MessageSquare/></span><div><p><b>Nadine</b> commented on your submission</p><small>Task 15 · 2h</small></div></article><article><span><Trophy/></span><div><p><b>3 builders</b> earned reputation</p><small>Developer Guild · 5h</small></div></article><article><span><FileText/></span><div><p><b>Redbelly Digest 04</b> was published</p><small>Ecosystem update · 1d</small></div></article></div></section></div>
  </div></MemberLayout>
}

export function MyTasksPage({ wallet }) {
  return <MemberLayout wallet={wallet}><div className="member-page"><div className="member-page-head"><div><Eyebrow>Contribution record</Eyebrow><h1>My tasks</h1><p>Track active work, submissions and completed contributions.</p></div><Link className="button button--primary" to="/taskboard">Find new work <ArrowRight size={16}/></Link></div><div className="dashboard-stats"><Stat label="Active" value="02"/><Stat label="In review" value="01"/><Stat label="Completed" value="06"/><Stat label="RBNT earned" value="1,840"/></div><section className="dash-panel task-timeline"><header><div><Eyebrow>Current cycle</Eyebrow><h2>Work in progress</h2></div></header>{tasks.slice(0,3).map((t,i)=><article key={t.id}><span className={`timeline-dot ${i===1?'is-review':''}`}/><div><span className="mono">{t.id}</span><StatusChip>{i===1?'Review':'In progress'}</StatusChip><h3>{t.title}</h3><p>{i===1?'Your submission is with the reviewer.':'Next milestone: responsive QA and repository handoff.'}</p></div><div><strong>{i===1?'Submitted':'6 days'}</strong><small>{i===1?'24 Aug':'remaining'}</small></div><ChevronRight/></article>)}</section></div></MemberLayout>
}

export function ProfilePage({ wallet }) {
  return <MemberLayout wallet={wallet}><div className="member-page"><div className="profile-banner"><div className="profile-avatar">AC</div><div><span className="eyebrow eyebrow--light">Community contributor</span><h1>Alex Contributor</h1><p className="mono">{wallet.address}</p></div><button className="button button--dark-outline"><Settings size={16}/> Edit profile</button></div><div className="profile-layout"><section><div className="dashboard-stats profile-stats"><Stat label="Reputation" value="42"/><Stat label="Contributions" value="09"/><Stat label="Votes cast" value="05"/></div><article className="dash-panel"><header><div><Eyebrow>Participation</Eyebrow><h2>Contribution history</h2></div></header><div className="contribution-list"><div><span className="icon-box"><Sparkles/></span><div><h3>DAO website redesign</h3><p>Design & strategy · In progress</p></div><StatusChip>In progress</StatusChip></div><div><span className="icon-box"><CheckCircle2/></span><div><h3>Developer troubleshooting wiki</h3><p>Documentation · Completed</p></div><b>+10 rep</b></div><div><span className="icon-box"><Vote/></span><div><h3>RCDP-06 vote</h3><p>Governance · Voted for</p></div><b>+2 rep</b></div></div></article></section><aside><article className="profile-card"><Eyebrow>Identity</Eyebrow><div><span>Wallet</span><b className="mono">{wallet.address.slice(0,9)}…{wallet.address.slice(-7)}</b></div><div><span>Network</span><b><i className="online-dot"/> {wallet.networkName}</b></div><div><span>Member since</span><b>March 2026</b></div><div><span>Primary guild</span><b>Builder Guild</b></div></article><article className="profile-card"><Eyebrow>Preferences & policies</Eyebrow><Link to="/resources">Notification settings <ChevronRight/></Link><Link to="/resources">Participation terms <ChevronRight/></Link><Link to="/resources">Privacy preferences <ChevronRight/></Link></article></aside></div></div></MemberLayout>
}

export function NotificationsPage({ wallet }) {
  const notifications = [
    { icon: Vote, title: 'Voting closes in 2 days', text: 'RCDP-07 needs your attention.', time: '12 min', unread: true },
    { icon: MessageSquare, title: 'New review comment', text: 'Nadine left feedback on TASK-15.', time: '2 hrs', unread: true },
    { icon: Zap, title: 'Task status changed', text: 'EligibilitySDK guide moved to review.', time: '5 hrs', unread: true },
    { icon: CheckCircle2, title: 'Proposal executed', text: 'Community Showcase pilot has been funded.', time: '1 day' },
  ]
  return <MemberLayout wallet={wallet}><div className="member-page"><div className="member-page-head"><div><Eyebrow>Member updates</Eyebrow><h1>Notifications</h1><p>Governance, task and community activity relevant to you.</p></div><button className="button button--secondary">Mark all as read</button></div><section className="dash-panel notification-list">{notifications.map(({icon:Icon,title,text,time,unread})=><article className={unread?'is-unread':''} key={title}><span className="icon-box"><Icon/></span><div><h3>{title}</h3><p>{text}</p></div><small>{time}</small>{unread&&<i/>}</article>)}</section></div></MemberLayout>
}
