import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { ArrowRight, BookMarked, BookOpen, CalendarDays, CheckCircle2, ChevronDown, CircleDollarSign, Clock3, Copy, Download, ExternalLink, FileCode2, FileText, Filter, GitBranch, GraduationCap, Network, Search, ShieldCheck, Sparkles, TrendingUp, Vote, Wrench } from 'lucide-react'
import { Breadcrumbs, Eyebrow, PageHero, SectionHeading, Stat, StatusChip, TextLink } from '../components/UI'
import { digestEditions, projects, proposals, resources, tasks, transactions } from '../data/content'

export function DigestPage() {
  return <><PageHero eyebrow="DAO Digest" title="The DAO, one month at a time." description="Decisions, contributions and momentum—edited into a clear public record." />
    <section className="section section--pull"><div className="container"><article className="digest-feature"><div className="digest-cover"><small>AUGUST 2026</small><span>DAO<br/>DIGEST</span><strong>04</strong><i>REDBELLY COMMUNITY</i></div><div className="digest-feature__copy"><Eyebrow>Latest edition</Eyebrow><h2>The contribution layer comes alive.</h2><p>Cycle 2 opens, the Taskboard evolves and three community-built developer resources ship. Plus: the vote shaping contributor rules and the builders to watch this month.</p><div className="digest-meta"><span><CalendarDays size={15}/> 27 August 2026</span><span><Clock3 size={15}/> 6 min read</span></div><button className="button button--primary">Read edition <ArrowRight size={17}/></button></div></article></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="Inside this edition" title="The signal, without the noise."/><div className="story-grid"><article className="story-card story-card--wide"><span className="story-number">01</span><div><span className="eyebrow">Governance</span><h3>Cycle 2 rules move to a community vote</h3><p>A clearer rubric, faster reviews and a public transparency ledger reshape how contribution work gets done.</p><TextLink to="/governance">Follow the proposal</TextLink></div></article><article className="story-card"><span className="story-number">02</span><div><span className="eyebrow">Builders</span><h3>Developer resources ship</h3><p>Troubleshooting, onboarding and integration guides move from tasks to useful public goods.</p></div></article><article className="story-card"><span className="story-number">03</span><div><span className="eyebrow">Treasury</span><h3>Where 28,750 RBNT went</h3><p>A plain-language breakdown of contributor and tooling spend this month.</p></div></article></div></div></section>
    <section className="section section--tint"><div className="container"><SectionHeading eyebrow="Archive" title="Previous editions"/><div className="edition-list">{digestEditions.slice(1).map(e => <article key={e.number}><span className="edition-no">{e.number}</span><div><small>{e.month}</small><h3>{e.title}</h3><p>{e.summary}</p></div><button className="icon-button"><ArrowRight/></button></article>)}</div></div></section>
  </>
}

export function ShowcasePage() {
  const [filter, setFilter] = useState('All projects')
  const filters = ['All projects', 'Platform', 'Developer tool', 'Protocol', 'Publication']
  const shown = filter === 'All projects' ? projects : projects.filter(p => p.type === filter)
  return <><PageHero eyebrow="Community showcase" title="See what the community is building." description="Working tools, bold experiments and shared resources made by Redbelly contributors." />
    <section className="section section--pull"><div className="container"><div className="filter-bar" role="group" aria-label="Filter projects">{filters.map(f => <button className={filter === f ? 'is-active' : ''} onClick={() => setFilter(f)} key={f}>{f}</button>)}</div><div className="project-grid">{shown.map((p, i) => <article className={`project-card project-card--${p.accent}`} key={p.title}><div className="project-art"><span>{p.mark}</span><small>0{i+1}</small></div><div className="project-card__body"><div><StatusChip tone="neutral">{p.type}</StatusChip><a href="#project"><ExternalLink size={16}/></a></div><h2>{p.title}</h2><p>{p.description}</p><footer><span>Built by</span><b>{p.maker}</b></footer></div></article>)}</div></div></section>
    <section className="section submit-project"><div className="container"><div><Eyebrow tone="light">Made something useful?</Eyebrow><h2>Put your work on the map.</h2><p>Show the community what you built, what changed and what you learned along the way.</p></div><button className="button button--light">Submit a project <ArrowRight size={17}/></button></div></section></>
}

export function TaskboardPage() {
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState('All')
  const shown = useMemo(() => tasks.filter(t => (status === 'All' || t.status === status) && t.title.toLowerCase().includes(query.toLowerCase())), [query, status])
  return <><PageHero eyebrow="Community Taskboard" title="Turn your skills into ecosystem impact." description="Browse public opportunities, understand the scope and contribute work that moves Redbelly forward."><div className="hero-inline-stats"><Stat label="Open now" value="06"/><Stat label="Cycle rewards" value="$1,240"/><Stat label="Ends in" value="18 days"/></div></PageHero>
    <section className="section section--pull"><div className="container"><div className="task-toolbar"><label className="search-input"><Search size={17}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search tasks"/></label><div className="select-wrap"><Filter size={16}/><select value={status} onChange={e => setStatus(e.target.value)}><option>All</option><option>Open</option><option>In progress</option><option>Review</option><option>Completed</option></select><ChevronDown size={15}/></div></div>
      <div className="task-board-layout"><aside><h3>Cycle 2</h3><div className="cycle-ring"><strong>18</strong><span>days left</span></div><p>Submissions close before the review window begins.</p><a href="https://redbelly-dao-taskboard.vercel.app/rules" target="_blank" rel="noreferrer">Read the rulebook <ExternalLink size={13}/></a><hr/><span>Completion</span><div className="progress"><i style={{width:'42%'}}/></div><small>8 of 19 tasks completed</small></aside><div className="task-cards">{shown.map(t => <article className="task-card" key={t.id}><header><span className="mono">{t.id}</span><StatusChip>{t.status}</StatusChip></header><h2>{t.title}</h2><p>{t.category}</p><div className="task-card__stats"><span><small>Reward</small><b>{t.reward} RBNT</b></span><span><small>Applicants</small><b>{t.applicants} / 5</b></span><span><small>Progress</small><b>{t.progress}%</b></span></div><div className="progress"><i style={{width:`${t.progress}%`}}/></div><footer><span>10 reputation points</span><button className="button button--secondary">View task <ArrowRight size={15}/></button></footer></article>)}</div></div>
    </div></section></>
}

export function TreasuryPage() {
  const [copied, setCopied] = useState(false)
  const copy = () => { navigator.clipboard?.writeText('0x71C4...9F20'); setCopied(true); setTimeout(() => setCopied(false), 1200) }
  return <><PageHero eyebrow="Public treasury" title="Every token accounted for." description="A clear view of DAO assets, allocations and spending—available to everyone, without connecting a wallet." />
    <section className="section section--pull"><div className="container"><div className="treasury-overview"><div><span>Total treasury value</span><strong>$284,392.18</strong><small><TrendingUp size={14}/> 4.8% this month</small></div><div className="treasury-stats"><Stat label="RBNT balance" value="2.41M" detail="$218,604"/><Stat label="Stablecoins" value="$51,288" detail="18.0% of treasury"/><Stat label="Committed" value="$14,500" detail="Current task cycle"/></div></div>
      <div className="chart-grid"><article className="chart-card"><header><div><span className="eyebrow">Treasury history</span><h2>Value over time</h2></div><select><option>Last 6 months</option></select></header><div className="line-chart"><div className="chart-y"><span>$300k</span><span>$250k</span><span>$200k</span><span>$150k</span></div><svg viewBox="0 0 700 230" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#c51d2a" stopOpacity=".25"/><stop offset="1" stopColor="#c51d2a" stopOpacity="0"/></linearGradient></defs><path className="area" d="M0 190 C90 176,120 158,190 166 S310 112,390 125 S520 70,700 47 L700 230 L0 230Z"/><path className="line" d="M0 190 C90 176,120 158,190 166 S310 112,390 125 S520 70,700 47"/></svg><div className="chart-x"><span>Mar</span><span>Apr</span><span>May</span><span>Jun</span><span>Jul</span><span>Aug</span></div></div></article><article className="allocation-card"><span className="eyebrow">Allocation</span><h2>Where funds are assigned</h2><div className="donut"><div><strong>76.8%</strong><span>Unallocated</span></div></div><ul><li><i className="ruby"/>Available <b>76.8%</b></li><li><i className="blue"/>Contributor rewards <b>12.4%</b></li><li><i className="gold"/>Operations <b>6.1%</b></li><li><i className="slate"/>Grants <b>4.7%</b></li></ul></article></div>
      <section className="transaction-section"><SectionHeading eyebrow="On-chain activity" title="Recent transactions" action={<button className="button button--secondary" onClick={copy}>{copied ? <CheckCircle2 size={15}/> : <Copy size={15}/>} {copied ? 'Copied' : 'Treasury address'}</button>}/><div className="data-table"><div className="data-row data-row--head"><span>Activity</span><span>Date</span><span>Amount</span><span>Status</span></div>{transactions.map(tx => <div className="data-row" key={tx.date}><span><span className="tx-icon"><CircleDollarSign size={16}/></span>{tx.type}</span><span>{tx.date}</span><span className="mono">{tx.amount}</span><span><StatusChip tone="confirmed">{tx.status}</StatusChip></span></div>)}</div></section>
    </div></section></>
}

export function GovernancePage() {
  return <><PageHero eyebrow="Governance" title="Decisions belong in the open." description="Understand what’s being proposed, how the community is voting and what happens next."><div className="hero-actions hero-actions--page"><button className="button button--light">View on Snapshot <ExternalLink size={15}/></button><button className="button button--dark-outline">How governance works</button></div></PageHero>
    <section className="section section--pull"><div className="container"><article className="active-proposal"><header><div><span className="live-badge"><i/> Voting now</span><span className="mono">RCDP-07</span></div><span><Clock3 size={15}/> Ends in 2d 14h</span></header><h2>Adopt Cycle 2 taskboard rules</h2><p>Approve the updated contribution framework covering review times, selection criteria, revision rights and public transparency.</p><div className="vote-bars"><div><span><b>For</b><em>78%</em></span><div><i style={{width:'78%'}}/></div></div><div><span><b>Against</b><em>22%</em></span><div><i style={{width:'22%'}}/></div></div></div><footer><span>1.28M RBNT voting power · 86 voters</span><button className="button button--primary">Review & vote <ArrowRight size={16}/></button></footer></article>
      <div className="governance-grid"><section><SectionHeading eyebrow="Proposal history" title="Recent decisions"/>{proposals.slice(1).map(p => <article className="proposal-row" key={p.id}><span className="proposal-check"><CheckCircle2/></span><div><span className="mono">{p.id}</span><h3>{p.title}</h3><p>{p.votes} · {p.yes}% voted for</p></div><StatusChip>{p.status}</StatusChip><ArrowRight size={18}/></article>)}</section><aside className="governance-guide"><span className="icon-box"><Vote/></span><span className="eyebrow">Your idea to a vote</span><h2>A clear path from discussion to decision.</h2><ol><li><span>01</span><div><b>Share the idea</b><p>Start a community discussion and test the need.</p></div></li><li><span>02</span><div><b>Shape the proposal</b><p>Define impact, budget and success criteria.</p></div></li><li><span>03</span><div><b>Community vote</b><p>Eligible members vote through Snapshot.</p></div></li><li><span>04</span><div><b>Execute & report</b><p>Approved work ships with public updates.</p></div></li></ol><button className="button button--secondary button--wide">Submit a proposal</button></aside></div>
    </div></section></>
}

export function DevelopersPage() {
  const [copied, setCopied] = useState(false)
  const copy = () => { navigator.clipboard?.writeText('https://governors.testnet.redbelly.network'); setCopied(true); setTimeout(() => setCopied(false), 1200) }
  return <><section className="dev-hero"><div className="dev-grid"/><div className="container"><div><Eyebrow tone="light">Developers · Start here</Eyebrow><h1>Build for real-world value.</h1><p>Everything you need to understand the network, connect to testnet and ship your first Redbelly application.</p><div className="hero-actions"><a className="button button--light" href="https://vine.redbelly.network" target="_blank" rel="noreferrer">Read the docs <ExternalLink size={15}/></a><a className="button button--dark-outline" href="https://github.com/redbellynetwork" target="_blank" rel="noreferrer"><GitBranch size={16}/> View GitHub</a></div></div><div className="code-window"><header><i/><i/><i/><span>connect.ts</span></header><pre><code><b>import</b> {'{ createPublicClient }'} <b>from</b> <em>'viem'</em>{'\n\n'}<b>const</b> redbelly = {'{'}{'\n'}  id: <strong>153</strong>,{'\n'}  name: <em>'Redbelly Testnet'</em>,{'\n'}  nativeCurrency: {'{'} symbol: <em>'RBNT'</em> {'}'},{'\n'}  rpcUrls: {'{'} default: {'{'} http: [rpcUrl] {'}'} {'}'}{'\n'}{'}'}</code></pre></div></div></section>
    <section className="section"><div className="container"><SectionHeading eyebrow="Your first hour" title="From curious to connected." description="A practical path with the right context at every step."/><div className="start-steps"><article><span>01</span><div className="icon-box"><GraduationCap/></div><h3>Understand Redbelly</h3><p>Learn why accountable participants and EVM compatibility matter for real-world assets.</p><a href="#learn">Network in 5 minutes <ArrowRight size={15}/></a></article><article><span>02</span><div className="icon-box"><Network/></div><h3>Connect to testnet</h3><p>Add the network, get test RBNT and confirm your setup before writing code.</p><a href="#network">Network setup <ArrowRight size={15}/></a></article><article><span>03</span><div className="icon-box"><FileCode2/></div><h3>Ship a contract</h3><p>Deploy an EVM-compatible contract and verify it on the explorer.</p><a href="#build">First deployment <ArrowRight size={15}/></a></article></div>
      <div className="network-panel" id="network"><div><Eyebrow>Testnet configuration</Eyebrow><h2>Connect your development environment</h2><p>Chain ID 153 is the current Redbelly Testnet environment used by the official developer documentation.</p><div className="network-fields"><label><span>Network name</span><code>Redbelly Testnet</code></label><label><span>Chain ID</span><code>153</code></label><label className="wide"><span>RPC URL</span><code>https://governors.testnet.redbelly.network</code><button onClick={copy}>{copied ? <CheckCircle2/> : <Copy/>}</button></label><label><span>Currency</span><code>RBNT</code></label></div></div><div className="network-caution"><ShieldCheck size={23}/><h3>Before you bridge or transact</h3><p>Verify network details against official documentation. Never share a seed phrase or private key.</p><a href="https://vine.redbelly.network" target="_blank" rel="noreferrer">Official documentation <ExternalLink size={13}/></a></div></div>
      <SectionHeading eyebrow="Developer toolkit" title="Find the right resource fast."/><div className="tool-grid"><a href="https://vine.redbelly.network" target="_blank" rel="noreferrer"><span className="icon-box"><BookOpen/></span><div><h3>Technical documentation</h3><p>Network concepts, SDKs and reference guides.</p></div><ExternalLink/></a><a href="https://github.com/redbellynetwork" target="_blank" rel="noreferrer"><span className="icon-box"><GitBranch/></span><div><h3>GitHub repositories</h3><p>Explore source code and working examples.</p></div><ExternalLink/></a><Link to="/resources"><span className="icon-box"><Wrench/></span><div><h3>Troubleshooting</h3><p>Fix common RPC, wallet and SDK issues.</p></div><ArrowRight/></Link><Link to="/taskboard"><span className="icon-box"><Sparkles/></span><div><h3>Developer tasks</h3><p>Contribute technical work to the ecosystem.</p></div><ArrowRight/></Link></div>
    </div></section></>
}

export function ResourcesPage() {
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('All')
  const categories = ['All', 'DAO essentials', 'Governance', 'Developers', 'Contributors']
  const shown = resources.filter(r => (category === 'All' || r.category === category) && r.title.toLowerCase().includes(query.toLowerCase()))
  return <><PageHero eyebrow="Resource hub" title="The knowledge base for participation." description="Essential documents, contributor guides and technical resources—organised around what you need to do." />
    <section className="section section--pull"><div className="container"><div className="resource-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search resources, guides and documents"/></div><div className="resource-layout"><aside><h3>Browse by category</h3>{categories.map(c => <button className={category === c ? 'is-active' : ''} onClick={()=>setCategory(c)} key={c}>{c}<span>{c === 'All' ? resources.length : resources.filter(r=>r.category===c).length}</span></button>)}</aside><div className="resource-list">{shown.map((r,i)=><article key={r.title}><span className="resource-icon">{i%2?<BookMarked/>:<FileText/>}</span><div><span className="eyebrow">{r.category}</span><h2>{r.title}</h2><p>{r.description}</p><small>{r.format}</small></div><button className="icon-button" aria-label={`Open ${r.title}`}>{r.format === 'External' ? <ExternalLink/> : <Download/>}</button></article>)}</div></div></div></section></>
}

export function AboutPage({ onJoin }) {
  return <><PageHero eyebrow="About the DAO" title="A community that earns influence through action." description="The Redbelly Community DAO brings builders, educators, researchers and organisers together around useful work for the network." />
    <section className="section section--pull"><div className="container"><div className="about-manifesto"><div><Eyebrow>Why we exist</Eyebrow><h2>Turn participation into progress.</h2></div><div><p>Redbelly is building infrastructure for a more accountable digital economy. The Community DAO makes that mission participatory: surfacing needs, funding useful work and keeping decisions visible.</p><p>You do not need to wait for permission to help. Start small, show your work and make it easier for the next person to build.</p></div></div><div className="about-stats"><Stat label="Community contributors" value="147"/><Stat label="Regions represented" value="23"/><Stat label="Completed tasks" value="31"/><Stat label="Governance decisions" value="07"/></div></div></section>
    <section className="section section--tint"><div className="container"><SectionHeading eyebrow="Operating principles" title="What we optimise for."/><div className="principle-list"><article><span>01</span><h3>We lead by building</h3><p>Credibility follows useful work, not titles.</p></article><article><span>02</span><h3>We share what we learn</h3><p>Public knowledge makes every contributor stronger.</p></article><article><span>03</span><h3>We respect time, talent and tokens</h3><p>Scopes, decisions and rewards should be clear.</p></article><article><span>04</span><h3>We design for the long term</h3><p>Reusable systems create compounding value.</p></article></div></div></section>
    <section className="section"><div className="container about-join"><div><Eyebrow tone="light">There’s a place for you</Eyebrow><h2>Come build the next chapter.</h2><p>Learn, contribute, govern or simply follow the work. You can start before connecting a wallet.</p></div><button className="button button--light" onClick={onJoin}>Join the DAO <ArrowRight/></button></div></section></>
}
